AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: >
  manchat-app-sync
  Sample SAM Template for manchat-app-sync

Parameters:
  ProjectName:
    Type: String
    Default: manchat-app-sync

Resources:
  AppSyncStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: app-sync/template.yaml
      Parameters:
        ProjectName: !Ref ProjectName

Outputs:
  GraphQLUrl:
    Description: AppSync Endpoint
    Value: !GetAtt AppSyncStack.Outputs.GraphQLUrl
