AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: >
  manchat-app-sync
  Sample SAM Template for manchat-app-sync

Parameters:
  ProjectName:
    Type: String
    Default: manchat-app-sync

Resources:
  # API
  AppSync:
    Type: AWS::AppSync::GraphQLApi
    Properties:
      Name: !Ref ProjectName
      AuthenticationType: AWS_LAMBDA
      LambdaAuthorizerConfig:
        AuthorizerUri: !GetAtt AppSyncAuthorizer.Arn
      LogConfig:
        CloudWatchLogsRoleArn: !GetAtt ServiceRoleStack.Outputs.ServiceRoleArn
        FieldLogLevel: ALL

  AppSyncAuthorizer:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: web-socket/lambda/authorizer
      Handler: index.handler
      Tracing: Active
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: Lambda Authorizer for AppSync
      FunctionName: appsync-authorizer
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Sub ${ProjectName}-connection-table
      Environment:
        Variables:
          TABLE_NAME: !Sub ${ProjectName}-connection-table
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Format: esm
        External:
          - '@aws-sdk/client-dynamodb'
          - '@aws-sdk/lib-dynamodb'
        Minify: false
        Target: es2022
        OutExtension:
          - .js=.mjs
        EntryPoints:
          - index.ts

  AppsyncPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt AppSyncAuthorizer.Arn
      Action: lambda:InvokeFunction
      Principal: appsync.amazonaws.com
      SourceAccount: !Ref AWS::AccountId
      SourceArn: !GetAtt AppSync.Arn

  # ApiKey
  AppSyncKey:
    Type: AWS::AppSync::ApiKey
    Properties:
      ApiId: !GetAtt AppSync.ApiId
      Description: API Key for Restaurant API

  # Schema
  AppSyncSchema:
    Type: AWS::AppSync::GraphQLSchema
    Properties:
      ApiId: !GetAtt AppSync.ApiId
      DefinitionS3Location: schema.graphql

  # ServiceRole
  ServiceRoleStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: web-socket/db/service-role/template.yaml
      Parameters:
        ProjectName: !Ref ProjectName
        ConnectionTableArn: !GetAtt TablesStack.Outputs.ConnectionTableArn
        UserTableArn: !GetAtt TablesStack.Outputs.UserTableArn
        RoomTableArn: !GetAtt TablesStack.Outputs.RoomTableArn
        ChatTableArn: !GetAtt TablesStack.Outputs.ChatTableArn

  TablesStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: web-socket/db/tables/template.yaml
      Parameters:
        ProjectName: !Ref ProjectName

  DataSourcesStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: web-socket/db/data-sources/template.yaml
      Parameters:
        ApiId: !GetAtt AppSync.ApiId
        ProjectName: !Ref ProjectName
        ServiceRoleArn: !GetAtt ServiceRoleStack.Outputs.ServiceRoleArn
        Region: !Ref AWS::Region

  # getConnections
  GetConnectionResolverStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: web-socket/query/get-connections/template.yaml
      Parameters:
        ApiId: !GetAtt AppSync.ApiId
        ConnectionTableDataSourceName: ConnectionTableDataSource
        RoomTableDataSourceName: RoomTableDataSource
    DependsOn:
      - AppSyncSchema

  # getRooms
  GetRoomsResolverStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: web-socket/query/get-rooms/template.yaml
      Parameters:
        ApiId: !GetAtt AppSync.ApiId
        ConnectionTableDataSourceName: ConnectionTableDataSource
        RoomTableDataSourceName: RoomTableDataSource
    DependsOn:
      - AppSyncSchema

  # addConnection
  AddConnectionResolverStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: web-socket/mutation/add-connection/template.yaml
      Parameters:
        ApiId: !GetAtt AppSync.ApiId
        ConnectionTableDataSourceName: ConnectionTableDataSource
    DependsOn:
      - AppSyncSchema

  # addRoom
  AddRoomResolverStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: web-socket/mutation/add-room/template.yaml
      Parameters:
        ApiId: !GetAtt AppSync.ApiId
        ConnectionTableDataSourceName: ConnectionTableDataSource
        RoomTableDataSourceName: RoomTableDataSource
    DependsOn:
      - AppSyncSchema

  # getUsers
  GetUsersResolverStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: web-socket/query/get-users/template.yaml
      Parameters:
        ApiId: !GetAtt AppSync.ApiId
        UserTableDataSourceName: UserTableDataSource
    DependsOn:
      - AppSyncSchema

Outputs:
  ApiEndpoint:
    Description: AppSync Endpoint
    Value: !GetAtt AppSync.GraphQLUrl

  ApiId:
    Description: AppSync API ID
    Value: !GetAtt AppSync.ApiId

  ApiKey:
    Description: AppSync API Key
    Value: !GetAtt AppSyncKey.ApiKey
