AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  manchat-app-sync
  Sample SAM Template for manchat-app-sync

Parameters:
  ApiId:
    Type: String
  ConnectionTableDataSourceName:
    Type: String
  RoomTableDataSourceName:
    Type: String

Resources:
  GetConnectionsQueryResolver:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !Ref ApiId
      TypeName: Query
      FieldName: "getConnections"
      DataSourceName: !Ref ConnectionTableDataSourceName
      RequestMappingTemplate: |
        {
          "version": "2017-02-28",
          "operation": "Scan",
          "limit": $util.defaultIfNull(${ctx.args.limit}, 20),
          "nextToken": $util.toJson($util.defaultIfNullOrBlank($ctx.args.nextToken, null))
        }
      ResponseMappingTemplate: |
        $util.toJson($ctx.result.items)

  # Connection.room
  ConnectionRoomQueryResolver:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !Ref ApiId
      TypeName: Connection
      FieldName: "room"
      DataSourceName: !Ref RoomTableDataSourceName
      RequestMappingTemplate: |
        {
          "version": "2017-02-28",
          "operation": "GetItem",
          "key": {
            "id": $util.dynamodb.toDynamoDBJson($ctx.source.roomId),
          }
        }
      ResponseMappingTemplate: |
        $util.toJson($ctx.result)
