version: '3.7'

services:
  work:
    build: .
    container_name: manchat-deploy-aws-work
    ports:
      - '3000:3000'
    volumes:
      - '.:/home/node/manchat-deploy-aws'
    env_file:
      - .env.work
    command: sh
    environment:
      AWS_DEFAULT_REGION: ap-northeast-1
      AWS_DEFAULT_OUTPUT: json