version: '3.7'

services:
  cdk:
    build: ./cdk
    container_name: manchat-deploy-aws-cdk
    ports:
      - '3000:3000'
    volumes:
      - './cdk:/home/node/manchat-deploy-aws/cdk'
    env_file:
      - .env.cdk
    command: sh
    environment:
      AWS_DEFAULT_REGION: ap-northeast-1
      AWS_DEFAULT_OUTPUT: json
  sam:
    build: ./sam
    container_name: manchat-deploy-aws-sam
    ports:
      - '3000:3000'
    volumes:
      - './sam:/sam'
    env_file:
      - .env.cdk
    command:
      - bash
      - -c
      - |
        echo "Launching aws-tools"
        sleep infinity
    environment:
      AWS_DEFAULT_REGION: ap-northeast-1
      AWS_DEFAULT_OUTPUT: json
  client:
    build: ./client
    container_name: manchat-client
    tty: true
    ports:
      - "82:3000"
      - "83:4173"
    volumes:
      - './client:/app'
    command: bash -c "npm run dev"
