AWSTemplateFormatVersion: 2010-09-09
Description: >-
  manchat
Transform:
- AWS::Serverless-2016-10-31

Parameters:
  TableName:
    Type: String

Resources:
  getAllSampleFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: get-all-sample.getAllSampleHandler
      Description: A simple example includes a HTTP get method to get all items from a DynamoDB table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TableName
      Environment:
        Variables:
          TABLE_NAME: !Ref TableName

  LambdaPermission:
    Type: "AWS::Lambda::Permission"
    Properties:
      Action: "lambda:InvokeFunction"
      FunctionName: !Ref getAllSampleFunction
      Principal: "apigateway.amazonaws.com"

Outputs:
  FunctionArn:
    Value: !GetAtt getAllSampleFunction.Arn

Globals:
  Function:
    Tracing: Active
    Runtime: nodejs18.x
    Architectures:
      - x86_64
    MemorySize: 128
    Timeout: 100
