AWSTemplateFormatVersion: 2010-09-09
Description: >-
  manchat
Transform:
- AWS::Serverless-2016-10-31

Parameters:
  BucketId:
    Type: String

Resources:
  RoomBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      BucketName: !Sub 'manchat-${BucketId}-room'
      Tags:
        - Key: CloudFormationArn
          Value: !Sub 'manchat-${BucketId}-room'

Outputs:
  RegionalDomainName:
    Value: !GetAtt RoomBucket.RegionalDomainName
