AWSTemplateFormatVersion: 2010-09-09
Description: >-
  manchat
Transform:
  - AWS::Serverless-2016-10-31

Resources:
  ConnectionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: connectionId
          AttributeType: S
      KeySchema:
        - AttributeName: connectionId
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      SSESpecification:
        SSEEnabled: True

Outputs:
  TableRef:
    Value: !Ref ConnectionsTable
