AWSTemplateFormatVersion: 2010-09-09
Description: >-
  manchat
Transform:
- AWS::Serverless-2016-10-31

# Resources declares the AWS resources that you want to include in the stack
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html
Resources:

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: 'true'

  FunctionGetAllSampleStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: sub_templates/rest-api/get-all-sample/template.yaml
      Parameters:
        TableName: !GetAtt DynamoDbSampleStack.Outputs.TableRef

  FunctionGetByIdStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: sub_templates/rest-api/get-by-id/template.yaml
      Parameters:
        TableName: !GetAtt DynamoDbSampleStack.Outputs.TableRef

  FunctionPutItemStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: sub_templates/rest-api/put-item/template.yaml
      Parameters:
        TableName: !GetAtt DynamoDbSampleStack.Outputs.TableRef

  ApiRESTStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: sub_templates/api-gateway/REST/template.yaml
      Parameters:
        FunctionGetAllSampleArn: !GetAtt FunctionGetAllSampleStack.Outputs.FunctionArn
        FunctionGetByIdArn: !GetAtt FunctionGetByIdStack.Outputs.FunctionArn
        FunctionPutItemArn: !GetAtt FunctionPutItemStack.Outputs.FunctionArn

  DynamoDbSampleStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: sub_templates/dynamo-db/sample/template.yaml

  S3BucketStaticStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: sub_templates/s3/static/template.yaml
      Parameters:
        BucketId: !Ref AWS::AccountId

  S3BucketRoomStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: sub_templates/s3/room/template.yaml
      Parameters:
        BucketId: !Ref AWS::AccountId

#  CloudFrontDistribution:
#    Type: AWS::CloudFront::Distribution
#    Properties:
#      DistributionConfig:
#        CacheBehaviors:
#          - Compress: true
#            PathPattern: '/api/*'
#            ViewerProtocolPolicy: 'allow-all'
#            TargetOriginId: ''
#        Origins:
#          - Id: CustomOrigin
#            DomainName: !Sub 'manchat.${AWS::AccountId}.amazonaws.com'
#            CustomOriginConfig:
#              HTTPPort: 80
#              OriginProtocolPolicy: http-only
#        Enabled: true
#        DefaultRootObject: index.html
#        Logging:
#          IncludeCookies: 'false'
#          Bucket: !Sub '${S3BucketAccesslogs}.s3-${AWS::Region}.amazonaws.com'
#          Prefix: !Sub 'cloudfront/${AWS::StackName}'
#        CustomErrorResponses:
#          - ErrorCachingMinTTL: 300
#            ErrorCode: 403
#            ResponseCode: 200
#            ResponsePagePath: /index.html
#        Comment: !Sub '${AWS::StackName}-distribution'
#        DefaultCacheBehavior:
#          TargetOriginId: CustomOrigin
#          ForwardedValues:
#            QueryString: false
#          DefaultTTL: 300
#          MaxTTL: 300
#          MinTTL: 300
#          ViewerProtocolPolicy: redirect-to-https
#        #Aliases:
#        #- dummy.example.com
#        #ViewerCertificate:
#        #  SslSupportMethod: sni-only
#        #  AcmCertificateArn: arn:aws:acm:us-east-1:000000000000:certificate/dummy-example-com
#      Tags:
#        - Key: CloudFormationArn
#          Value: !Sub '${AWS::StackName}'

#Outputs:
#  WebEndpoint:
#    Description: API Gateway endpoint URL for Prod stage
#    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
# # More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Tracing: Active
  Api:
    TracingEnabled: true
