AWSTemplateFormatVersion: 2010-09-09
Description: >-
  manchat
Transform:
- AWS::Serverless-2016-10-31

Resources:
  # CloudWatch
  CloudWatchStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: cloud-watch/template.yaml
      Parameters:
        StackName: !Ref AWS::StackName

  # OAI
  CloudFrontOriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Ref AWS::StackName

  # CloudFront
  CloudFrontDistributionStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: cloud-front/template.yaml
      Parameters:
        RESTApiDomainName: !GetAtt RESTApiStack.Outputs.DomainName
        StaticBucketDomainName: !GetAtt StaticBucketStack.Outputs.RegionalDomainName
        RoomBucketDomainName: !GetAtt RoomBucketStack.Outputs.RegionalDomainName
        OAI: !GetAtt CloudFrontOriginAccessIdentity.Id

  # S3
  StaticBucketStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: s3/static/template.yaml
      Parameters:
        AccountId: !Ref AWS::AccountId
        OAI: !GetAtt CloudFrontOriginAccessIdentity.Id
  RoomBucketStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: s3/room/template.yaml
      Parameters:
        AccountId: !Ref AWS::AccountId
        OAI: !GetAtt CloudFrontOriginAccessIdentity.Id

  # DynamoDB
  DynamoDbSampleStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: dynamo-db/sample/template.yaml
  DynamoDbConnectionStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: dynamo-db/connection/template.yaml

  # Server Sources
  RESTApiStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: rest-api/template.yaml
      Parameters:
        DynamoDbSampleStackRef: !GetAtt DynamoDbSampleStack.Outputs.TableRef
#  WebSocketStack:
#    Type: AWS::Serverless::Application
#    Properties:
#      Location: web-socket/template.yaml
#      Parameters:
#        DynamoDbSampleStackRef: !GetAtt DynamoDbSampleStack.Outputs.TableRef

  ##
  # WebSocket
  ##

  # API Gateway
  ApiGatewayWebSocketStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: web-socket/gateway/template.yaml

  # Lambda
  FunctionConnectStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: web-socket/$connect/template.yaml
      Parameters:
        WebSocketApiId: !GetAtt ApiGatewayWebSocketStack.Outputs.ApiId
        TableName: !GetAtt DynamoDbConnectionStack.Outputs.TableRef
    DependsOn:
      - ApiGatewayWebSocketStack

  FunctionDisconnectStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: web-socket/$disconnect/template.yaml
      Parameters:
        WebSocketApiId: !GetAtt ApiGatewayWebSocketStack.Outputs.ApiId
        TableName: !GetAtt DynamoDbConnectionStack.Outputs.TableRef
    DependsOn:
      - ApiGatewayWebSocketStack

  FunctionSendMessageStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: web-socket/send-message/template.yaml
      Parameters:
        WebSocketApiId: !GetAtt ApiGatewayWebSocketStack.Outputs.ApiId
        TableName: !GetAtt DynamoDbConnectionStack.Outputs.TableRef
    DependsOn:
      - ApiGatewayWebSocketStack

  Deployment:
    Type: AWS::ApiGatewayV2::Deployment
    Properties:
      ApiId: !GetAtt ApiGatewayWebSocketStack.Outputs.ApiId
    DependsOn:
      - FunctionConnectStack
      - FunctionDisconnectStack
      - FunctionSendMessageStack

  Stage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      StageName: Prod
      Description: Prod Stage
      DeploymentId: !Ref Deployment
      ApiId: !GetAtt ApiGatewayWebSocketStack.Outputs.ApiId

Outputs:
  CloudFrontAccessUrl:
    Value: !GetAtt CloudFrontDistributionStack.Outputs.AccessUrl
  RESTApiDirectUrl:
    Description: To call the REST API by API Gateway.
    Value: !GetAtt RESTApiStack.Outputs.RESTApiDirectUrl
  WebSocketDirectUrl:
    Description: To call the REST API by API Gateway.
    Value: !Sub wscat -c ${ApiGatewayWebSocketStack.Outputs.ProdDataEndpoint}
