AWSTemplateFormatVersion: 2010-09-09
Description: >-
  manchat
Transform:
- AWS::Serverless-2016-10-31

Resources:
  # CloudWatch
  CloudWatchStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: cloud-watch/template.yaml
      Parameters:
        StackName: !Ref AWS::StackName

  # OAI
  CloudFrontOriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Ref AWS::StackName

  # CloudFront
  CloudFrontDistributionStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: cloud-front/template.yaml
      Parameters:
        RESTApiDomainName: !GetAtt RESTApiStack.Outputs.DomainName
        StaticBucketDomainName: !GetAtt StaticBucketStack.Outputs.RegionalDomainName
        RoomBucketDomainName: !GetAtt RoomBucketStack.Outputs.RegionalDomainName
        OAI: !GetAtt CloudFrontOriginAccessIdentity.Id

  # S3
  StaticBucketStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: s3/static/template.yaml
      Parameters:
        AccountId: !Ref AWS::AccountId
        OAI: !GetAtt CloudFrontOriginAccessIdentity.Id
  RoomBucketStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: s3/room/template.yaml
      Parameters:
        AccountId: !Ref AWS::AccountId
        OAI: !GetAtt CloudFrontOriginAccessIdentity.Id

  # DynamoDB
  DynamoDbSampleStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: dynamo-db/sample/template.yaml
  DynamoDbConnectionStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: dynamo-db/connection/template.yaml

  # Server Sources
  RESTApiStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: rest-api/template.yaml
      Parameters:
        DynamoDbSampleStackRef: !GetAtt DynamoDbSampleStack.Outputs.TableRef
  WebSocketStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: web-socket/template.yaml
      Parameters:
        TableName: !GetAtt DynamoDbConnectionStack.Outputs.TableRef

Outputs:
  CloudFrontAccessUrl:
    Value: !GetAtt CloudFrontDistributionStack.Outputs.AccessUrl
  RESTApiDirectUrl:
    Description: To call the REST API by API Gateway.
    Value: !GetAtt RESTApiStack.Outputs.RESTApiDirectUrl
  WebSocketCommand:
    Description: To call the WebSocket by API Gateway.
    Value: !Ref wscat -c ${WebSocketStack.Outputs.ProdDataEndpoint}
