AWSTemplateFormatVersion: 2010-09-09
Description: >-
  manchat
Transform:
- AWS::Serverless-2016-10-31

Resources:
  # CloudWatch
  CloudWatchStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: cloud-watch/template.yaml
      Parameters:
        StackName: !Ref AWS::StackName

  # OAI
  CloudFrontOriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Ref AWS::StackName

  # CloudFront
  CloudFrontDistributionStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: cloud-front/template.yaml
      Parameters:
        RESTfulApiDomainName: !GetAtt ApiRESTStack.Outputs.DomainName
        StaticBucketDomainName: !GetAtt StaticBucketStack.Outputs.RegionalDomainName
        RoomBucketDomainName: !GetAtt RoomBucketStack.Outputs.RegionalDomainName
        OAI: !GetAtt CloudFrontOriginAccessIdentity.Id

  # S3
  StaticBucketStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: s3/static/template.yaml
      Parameters:
        AccountId: !Ref AWS::AccountId
        OAI: !GetAtt CloudFrontOriginAccessIdentity.Id

  RoomBucketStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: s3/room/template.yaml
      Parameters:
        AccountId: !Ref AWS::AccountId
        OAI: !GetAtt CloudFrontOriginAccessIdentity.Id

  # API Gateway
  ApiRESTStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: rest-api/gateway/template.yaml
      Parameters:
        FunctionGetAllSampleArn: !GetAtt FunctionGetAllSampleStack.Outputs.FunctionArn
        FunctionGetByIdArn: !GetAtt FunctionGetByIdStack.Outputs.FunctionArn
        FunctionPutItemArn: !GetAtt FunctionPutItemStack.Outputs.FunctionArn

  # Lambda
  FunctionGetAllSampleStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: rest-api/get-all-sample/template.yaml
      Parameters:
        TableName: !GetAtt DynamoDbSampleStack.Outputs.TableRef

  FunctionGetByIdStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: rest-api/get-by-id/template.yaml
      Parameters:
        TableName: !GetAtt DynamoDbSampleStack.Outputs.TableRef

  FunctionPutItemStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: rest-api/put-item/template.yaml
      Parameters:
        TableName: !GetAtt DynamoDbSampleStack.Outputs.TableRef

  # DynamoDB
  DynamoDbSampleStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: dynamo-db/sample/template.yaml

Outputs:
  CloudFrontAccessUrl:
    Value: !GetAtt CloudFrontDistributionStack.Outputs.AccessUrl
  RESTfulApiDirectUrl:
    Description: To call the REST API by API Gateway.
    Value: !Sub ${ApiRESTStack.Outputs.ProdDataEndpoint}/api
