AWSTemplateFormatVersion: 2010-09-09
Description: >-
  manchat
Transform:
  - AWS::Serverless-2016-10-31

Parameters:
  FunctionGetAllSampleArn:
    Type: String
  FunctionGetByIdArn:
    Type: String
  FunctionPutItemArn:
    Type: String

Resources:
  ApiREST:
    Type: AWS::Serverless::Api
    Properties:
      Name: manchat-REST-API
      StageName: Prod
      DefinitionBody:
        openapi: '3.0'
        info: {}
        paths:
          /api/:
            get:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri: !Sub arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${FunctionGetAllSampleArn}/invocations
              responses: {}
            post:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri: !Sub arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${FunctionPutItemArn}/invocations
              responses: {}
          /api/{id}:
            get:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri: !Sub arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${FunctionGetByIdArn}/invocations
              responses: {}

Outputs:
  ProdDataEndpoint:
    Value: !Sub https://${ApiREST}.execute-api.${AWS::Region}.amazonaws.com/Prod
  DomainName:
    Value: !Sub ${ApiREST}.execute-api.${AWS::Region}.amazonaws.com
