AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: >
  manchat-app-sync
  Sample SAM Template for manchat-app-sync

Parameters:
  ApiId:
    Type: String
  RoomTableDataSourceName:
    Type: String

Resources:
  GetRoomsQueryResolver:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !Ref ApiId
      TypeName: Query
      FieldName: getRoom
      DataSourceName: !Ref RoomTableDataSourceName
      RequestMappingTemplateS3Location: ../vtl/query-where-token-input-room-token.vm
      ResponseMappingTemplateS3Location: ../vtl/return-result-items-first.vm
