AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: >
  manchat-app-sync
  Sample SAM Template for manchat-app-sync

Parameters:
  ConnectionTableArn:
    Type: String
  UserTableArn:
    Type: String
  RoomTableArn:
    Type: String
  ChatTableArn:
    Type: String

Resources:
  AppSyncServiceRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      RoleName: manchat-app-sync-role
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSAppSyncPushToCloudWatchLogs
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - sts:AssumeRole
            Principal:
              Service:
                - appsync.amazonaws.com
      Policies:
        - PolicyName: manchat-app-sync-role-ddb-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:BatchGetItem
                  - dynamodb:Query
                  - dynamodb:Scan
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                Resource:
                  - !Sub ${ConnectionTableArn}
                  - !Sub ${ConnectionTableArn}/*
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:BatchGetItem
                  - dynamodb:Query
                  - dynamodb:Scan
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                Resource:
                  - !Sub ${UserTableArn}
                  - !Sub ${UserTableArn}/*
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:BatchGetItem
                  - dynamodb:Query
                  - dynamodb:Scan
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                Resource:
                  - !Sub ${RoomTableArn}
                  - !Sub ${RoomTableArn}/*
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:BatchGetItem
                  - dynamodb:Query
                  - dynamodb:Scan
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                Resource:
                  - !Sub ${ChatTableArn}
                  - !Sub ${ChatTableArn}/*

Outputs:
  ServiceRoleArn:
    Value: !GetAtt AppSyncServiceRole.Arn
