AWSTemplateFormatVersion: 2010-09-09
Description: >-
  manchat
Transform:
- AWS::Serverless-2016-10-31

Parameters:
  BucketId:
    Type: String

Resources:
  StaticBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      BucketName: !Sub 'manchat-${BucketId}-static'
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: 404.html
      Tags:
        - Key: CloudFormationArn
          Value: !Sub 'manchat-${BucketId}-static'

Outputs:
  RegionalDomainName:
    Value: !GetAtt StaticBucket.RegionalDomainName
